# Generated by Django 6.0.6 on 2026-06-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swappit_api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('exchange', 'author')},
        ),
    ]
