# Generated by Django 6.0.5 on 2026-05-27 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Furniture', 'Furniture'), ('Books', 'Books'), ('Music', 'Music'), ('Sports', 'Sports'), ('Other', 'Other')], default='Other', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair')], default='Good', max_length=10)),
                ('value', models.PositiveIntegerField(help_text='Estimated value in XAF (FCFA)')),
                ('emoji', models.CharField(default='📦', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
            },
        ),
    ]
