# Generated by Django 6.0.6 on 2026-06-05 23:28

import swappit_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swappit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', swappit_api.models.UserManager()),
            ],
        ),
    ]
